---
title: "103_project_final_submission"
author: "Rob Ross-Shannon"
date: "2024-08-20"
output: pdf_document
---

```{r}
library(dplyr)
library(kableExtra)
library(pheatmap)
library(ggpubr)
library(ggplot2)
library(ggExtra)

#Reading in data sets
setwd("/Users/Rob Ross-Shannon/Documents/GitHub/103_Project")
genes <- read.csv("~/Documents/GitHub/103_Project/QBS103_GSE157103_genes.csv")
series_matrix <- read.csv("~/Documents/GitHub/103_Project/QBS103_GSE157103_series_matrix.csv")

#Cleaning data set (row names)
rownames(genes) <- genes$X
genes <- select(genes, -c('X'))

#Transposing data set and renaming index
genesT <- as.data.frame(t(genes))
genesT$participant_id <- rownames(genesT)

#Fixing typo in data set
genesT$participant_id[which(genesT$participant_id=="COVID_06_.y_male_NonICU")] <- "COVID_06_:y_male_NonICU"

#Combing the data sets into one data frame
combinedData <- inner_join(genesT, series_matrix, by = "participant_id")
head(combinedData)
```

```{r}
cont_summary_df <- combinedData[(combinedData$age != ' :') & (combinedData$age != ' >89'),]
cont_summary_df <- cont_summary_df[(cont_summary_df$procalcitonin.ng.ml.. != 'unknown'),]
cont_summary_df <- select(cont_summary_df, c('hospital.free_days_post_45_day_followup', 'age', 'procalcitonin.ng.ml..', 'sex'))
cont_summary_df$age <- as.numeric(cont_summary_df$age)
cont_summary_df$procalcitonin.ng.ml.. <- as.numeric(cont_summary_df$procalcitonin.ng.ml..)
cat_summary_df <- select(combinedData, c('icu_status', 'disease_status', 'sex')) 

#Checking the distrubution of continuous variables
#Non normally distributed
# ggplot(data = combinedData,aes(x = hospital.free_days_post_45_day_followup)) +
#   geom_histogram(binwidth = 5) + 
#   labs(x = 'Continuous Variable 1',y = 'Frequency') +
#   theme_classic()
# combinedData$hospital.free_days_post_45_day_followup

# df_filtered <- combinedData[(combinedData$age != ' :') & (combinedData$age != ' >89'),]
# df_filtered$age <- as.numeric(df_filtered$age)
# #Non normally distributed
# ggplot(data = df_filtered, aes(x=age)) +
#   geom_histogram(binwidth = 5) + 
#   labs(x = 'Continuous Variable 1',y = 'Frequency') +
#   theme_classic()

# df_filtered <- combinedData[(combinedData$procalcitonin.ng.ml.. != 'unknown'),]
# df_filtered$procalcitonin.ng.ml.. <- as.numeric(df_filtered$procalcitonin.ng.ml..)
# df_filtered$procalcitonin.ng.ml..
# #Non normally distributed
# ggplot(data = df_filtered, aes(x=procalcitonin.ng.ml..)) +
#   geom_histogram(binwidth = 5) + 
#   labs(x = 'Continuous Variable 1',y = 'Frequency') +
#   theme_classic()


# Define a function to median (all variables are non-normally distributed)
contSummary <- function(x) {
  # Calculate median (IQR) if non-normally distributed

    # Calculate individual values
    myMedian <- round(median(x),2)
    myIQR <- round(IQR(x),2)
    # Combine values
    paste0(myMedian,' [',myIQR,']')
}

contsummary_male <- cont_summary_df %>%
  filter(sex == ' male') %>%
  select(c('hospital.free_days_post_45_day_followup', 'age', 'procalcitonin.ng.ml..'))%>%
  apply(MARGIN = 2, FUN = contSummary)
contsummary_male <- as.data.frame(contsummary_male)

contsummary_female <- cont_summary_df %>%
  filter(sex == ' female') %>%
  select(c('hospital.free_days_post_45_day_followup', 'age', 'procalcitonin.ng.ml..'))%>%
  apply(MARGIN = 2, FUN = contSummary)
contsummary_female <- as.data.frame(contsummary_female)

colnames(contsummary_male) <- c('Male')
colnames(contsummary_female) <- c('Female')
rownames(contsummary_male) <- c('Hospital Free Days (Post 45 Day Followup) Median [IQR]', 'Age (yrs) Median [IQR]', 'Procalcitonin (ng/mL) Median [IQR]')
rownames(contsummary_female) <- c('Hospital Free Days (Post 45 Day Followup) Median [IQR]', 'Age (yrs) Median [IQR]', 'Procalcitonin (ng/mL) Median [IQR]')

contsummary_female$Male <- contsummary_male[rownames(contsummary_female), "Male"]



catSummary <- function(x) {
  # Calculate median (IQR) if non-normally distributed

    # Calculate individual values
    n <- table(x)
    perc <-round(prop.table(n) *100, 2)
    # Combine values
    paste0(n,' (',perc,')')
}

catsummary_sex <- cat_summary_df %>%
  select(c('sex')) %>%
  apply(MARGIN = 2, FUN = catSummary)
catsummary_sex <- as.data.frame(t(catsummary_sex))

catsummary_maleicu <- cat_summary_df %>%
  filter(sex == ' male') %>%
  select(c('icu_status'))%>%
  apply(MARGIN = 2, FUN = catSummary)
catsummary_maleicu <- as.data.frame(catsummary_maleicu)

catsummary_maledisease <- cat_summary_df %>%
  filter(sex == ' male') %>%
  select(c('disease_status'))%>%
  apply(MARGIN = 2, FUN = catSummary)
catsummary_maledisease <- as.data.frame(catsummary_maledisease)

catsummary_femaleicu <- cat_summary_df %>%
  filter(sex == ' female') %>%
  select(c('icu_status'))%>%
  apply(MARGIN = 2, FUN = catSummary)
catsummary_femaleicu <- as.data.frame(catsummary_femaleicu)

catsummary_femaledisease <- cat_summary_df %>%
  filter(sex == ' female') %>%
  select(c('disease_status'))%>%
  apply(MARGIN = 2, FUN = catSummary)
catsummary_femaledisease <- as.data.frame(catsummary_femaledisease)

rownames(catsummary_sex) <- c('Sex n(%)')
rownames(catsummary_femaleicu) <- c('Yes', 'No')
rownames(catsummary_maleicu) <- c('Yes', 'No')
rownames(catsummary_femaledisease) <- c('COVID-19', 'Non-COVID-19')
rownames(catsummary_maledisease) <- c('COVID-19','Non-COVID-19')

colnames(catsummary_sex) <- c('Female', 'Male', 'Unknown')
colnames(catsummary_femaleicu) <- c('Female')
colnames(catsummary_femaledisease) <- c('Female')
colnames(catsummary_maleicu) <- c('Male')
colnames(catsummary_maledisease) <- c('Male')

catsummary_sex <- select(catsummary_sex, c(-Unknown))

catsummary_femaledisease$Male <- catsummary_maledisease[rownames(catsummary_femaledisease), "Male"]
catsummary_femaleicu$Male <- catsummary_maleicu[rownames(catsummary_femaleicu), "Male"]



summarydf <- bind_rows(catsummary_sex, catsummary_femaledisease, catsummary_femaleicu, contsummary_female)
new_row <- data.frame(Name = "Disease Status n(%)", Male = " ", Female = " ")
new_row1 <- data.frame(Name = "ICU Status n(%)", Male = " ", Female = " ")
rownames(new_row) <- new_row$Name
new_row <- select(new_row, c(-Name))
rownames(new_row1) <- new_row1$Name
new_row1 <- select(new_row1, c(-Name))

summarydf <- rbind(
  summarydf[1, ],         # Rows before the second position
  new_row, 
  summarydf[2:nrow(summarydf), ] # Rows after the second position
)
summarydf

summarydf <- rbind(
  summarydf[1:4, ],         # Rows before the fifth position
  new_row1, 
  summarydf[5:nrow(summarydf), ] # Rows after the fifth position
)


summarydf

tab <- kable(x = summarydf, caption = 'Summary Table',
             format = 'latex',booktabs = T,
             col.names = c("Female", "Male"),
             align = c('l','r'),escape = T) %>%
  add_indent(positions = c(3,4, 6,7),level_of_indent = 1)
tab
```

```{r}

#Selecting covariates of interest
covariates <- series_matrix[, c("participant_id","sex", "icu_status", "hospital.free_days_post_45_day_followup")]

#Selecting gene of interest
gene_of_interest <- select(genesT, c("AAAS", "participant_id"))

#linking gene and covariate data set
combinedData1 <- inner_join(gene_of_interest, covariates, by = "participant_id")
head(combinedData)
#Removing any unknown values from sex dataset
cleanedData <- combinedData1[combinedData1$sex != " unknown",]
```

```{r}
   #Creating project theme for plots

  project_theme <- theme(
    panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, face = "bold"),
    # Define my axis
    title = element_text(colour = "white"),
    axis.line = element_line(colour = "white", linewidth = rel(1)),
    axis.title = element_text(colour = "white"),
    axis.text = element_text(color = "white"),
    axis.ticks = element_line(colour = "white"),
    # Set plot background
    plot.background = element_rect(fill = "black"),
    panel.background = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(colour = "white"),
    legend.background = element_rect(fill = "black"),
    legend.title = element_text(colour = "white", ),
    # Move legend
    legend.position = 'right')

project_plots <- function(df_name, gene_name, cont_covariate, cat_covariate1, cat_covariate2){
  
  #Filtering just for inputs of interest
  cleanedData <- select(df_name, c(gene_name, cont_covariate, cat_covariate1, cat_covariate2))

  #Code to create histogram
  annotations <- data.frame(
    x = c(round(min(cleanedData[[gene_name]]), 2), round(mean(cleanedData[[gene_name]]), 2),
          round(max(cleanedData[[gene_name]]), 2)),
    y = c(4, 12, 5),
    label = c("Min:", "Mean:", "Max:"))

  #Creating histogram
  histogram <- ggplot(cleanedData,aes_string(x = gene_name)) +
    geom_histogram(aes(fill = ..count..), bins = 25)+
    #Creating gradient color representation
    scale_fill_gradient("Count", low = "blue", high = "red")+
    geom_text(data = annotations, aes(x = x, y = y, label = paste(label, x)), size = 3, 
              fontface = "bold", color = "white")+
    labs(x = paste0(gene_name,' Gene Expression'),y = 'Gene Frequency Count', 
         title = paste0(gene_name,' Gene Frequency Histogram'))+
    project_theme
  print(histogram)

  #Code to create scatter plot
  scatterplot <- ggplot(cleanedData,aes_string(x = gene_name,y = cont_covariate, colour = gene_name)) +
    geom_point()+
    #Creating gradient color representation
    scale_color_gradient(low = "blue", high = "red")+
    scale_x_continuous("Gene Frequency")+
    scale_y_continuous('Hospital Free Days (Post 45 Day Followup)')+
    labs(title = paste('Gene Expression AAAS vs. Hospital Free Days (Post 45 Day Followup)'))+
    #Creating smooth trendline
    geom_smooth(aes(color=..y..), method = "loess", se = FALSE)+
    project_theme
  print(scatterplot)

  #Code to create boxplot
  boxplot <- ggplot(cleanedData,aes_string(x = cat_covariate1,y = gene_name,fill = cat_covariate2)) +
    # Add box plot
    geom_boxplot(color = "white") +
    scale_fill_manual(values = c("red", "purple"))+
    # Change labels
    labs(x = 'Sex',y = 'AAAS Gene Frequency' ,fill = 
           'ICU Status', title = 'AAAS Gene Frequency by Sex and ICU Status')+
    project_theme
  print(boxplot)
}
#Creating loop to go though multiple genes

project_plots(df_name = cleanedData, gene_name = 'AAAS', cont_covariate = 
    'hospital.free_days_post_45_day_followup', cat_covariate1 = 'sex', cat_covariate2 = 'icu_status')
```

```{r}
combinedData
genes <- c('A1BG', 'AAAS', 'AACS', 'AAGAB', 'AAMP', 'AAK1', 'AAR2', 'AARS1', 'AATF', 'AATK', 'ABAT')
hmData <- select(combinedData, c(genes, 'participant_id'))
rownames(hmData) <- hmData$participant_id
hmData <- hmData %>% select(-participant_id)
hmData <- as.data.frame(t(hmData))

# Define covariate for tracking bar
annotationData <- data.frame(row.names = colnames(hmData),
                             'ICU Status' = combinedData$icu_status, 
                             'Sex' = combinedData$sex)
combinedData$s
# Define color palette
annotationColors <- list(ICU.Status = c(" no" = 'yellow',
                                    " yes" = 'lightblue'),
                         Sex = c(" male" = 'orange',
                                 " female" = 'lightgreen', ' unknown' = "red"))
# Generate heatmap
pheatmap(hmData,
         clustering_distance_cols = 'euclidean',
         clustering_distance_rows = 'euclidean',
         annotation_col = annotationData,
         annotation_colors = annotationColors,
         fontsize_col = 2,
         color = colorRampPalette(c("blue", "purple", "red"))(100),
         main = "Heatmap of Gene Expression Categorized by Sex and ICU Status")
```
```{r}
# Grouped Scatter plot with marginal density plots
# plot <- ggscatterhist(
#   cleanedData, x = "AAAS", y = "hospital.free_days_post_45_day_followup",
#   color = "icu_status", size = 3, alpha = 0.6,
#   palette = c("red", "purple", "#FC4E07"),
#   margin.params = list(fill = "icu_status", color = "black", size = 0.2), 
#   xlab = 'AAAS Gene Frequency',
#   ylab = 'Hospital Free Days (Post 45 Day Followup)', 
#   legend.title = list(color = "ICU Status")
#   )
# Create the scatter plot with a trendline using ggplot2
p <- ggplot(cleanedData, aes(x = AAAS, y = hospital.free_days_post_45_day_followup, color = icu_status)) +
  geom_point(size = 3, alpha = 0.6) +  # Scatter plot
  geom_smooth(method = "loess", se = FALSE, color = "black") +  # Add trendline
  scale_color_manual(values = c("blue", "red")) +  # Custom color palette
  labs(
    x = 'AAAS Gene Frequency', 
    y = 'Hospital Free Days (Post 45 Day Followup)', 
    color = 'ICU Status', # Change legend title
    title = "AAAS Gene Freq. vs. Hospital Free Days (by ICU Status)"
  ) +
  theme_minimal()+
  theme(
    plot.title = element_text(
      face = "bold",
      hjust = 0.5,
      vjust = 0.5
    )
  )+
  theme(legend.position = "top")

# Add marginal histograms or density plots using ggMarginal
p_with_margins <- ggMarginal(
  p, 
  type = "density",  # Type of marginal plots ('histogram', 'density', or 'boxplot')
  groupFill = TRUE  # Automatically group the fill by the 'color' aesthetic
)

# Display the final plot
print(p_with_margins)
```

