---
title: "103_Project_Submission2"
author: "Rob Ross-Shannon"
date: "2024-08-06"
output: pdf_document
---

```{r}
library(dplyr)
library(tidyverse)

#Reading in data sets
setwd("/Users/Rob Ross-Shannon/Documents/GitHub/103_Project")
genes <- read.csv("~/Documents/GitHub/103_Project/QBS103_GSE157103_genes.csv")
series_matrix <- read.csv("~/Documents/GitHub/103_Project/QBS103_GSE157103_series_matrix.csv")

#Cleaning data set (row names)
rownames(genes) <- genes$X
genes <- select(genes, -c('X'))

#Transposing data set and renaming index
genesT <- as.data.frame(t(genes))
genesT$participant_id <- rownames(genesT)

#Combing the data sets into one data frame
combinedData <- inner_join(genesT, series_matrix, by = "participant_id")
head(combinedData)
```


```{r}
project_plots <- function(df_name, gene_name, cont_covariate, cat_covariate1, cat_covariate2){
  
  #Filtering just for inputs of interest
  cleanedData <- select(df_name, c(gene_name, cont_covariate, cat_covariate1, cat_covariate2))
   #Creating project theme for plots
  project_theme <- theme(
    panel.border = element_blank(), panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, face = "bold"),
    # Define my axis
    title = element_text(colour = "white"),
    axis.line = element_line(colour = "white", linewidth = rel(1)),
    axis.title = element_text(colour = "white"),
    axis.text = element_text(color = "white"),
    axis.ticks = element_line(colour = "white"),
    # Set plot background
    plot.background = element_rect(fill = "black"),
    panel.background = element_blank(),
    legend.key = element_blank(),
    legend.text = element_text(colour = "white"),
    legend.background = element_rect(fill = "black"),
    legend.title = element_text(colour = "white", ),
    # Move legend
    legend.position = 'right')

  #Code to create histogram
  annotations <- data.frame(
    x = c(round(min(cleanedData[[gene_name]]), 2), round(mean(cleanedData[[gene_name]]), 2),
          round(max(cleanedData[[gene_name]]), 2)),
    y = c(4, 12, 5),
    label = c("Min:", "Mean:", "Max:"))

  #Creating histogram
  histogram <- ggplot(cleanedData,aes_string(x = gene_name)) +
    geom_histogram(aes(fill = ..count..), bins = 25)+
    #Creating gradient color representation
    scale_fill_gradient("Count", low = "blue", high = "red")+
    geom_text(data = annotations, aes(x = x, y = y, label = paste(label, x)), size = 3, 
              fontface = "bold", color = "white")+
    labs(x = paste0(gene_name,' Gene Frequency'),y = 'Gene Frequency Count', 
         title = paste0(gene_name,' Gene Frequency Histogram'))+
    project_theme
  print(histogram)

  #Code to create scatter plot
  scatterplot <- ggplot(cleanedData,aes_string(x = gene_name,y = cont_covariate, colour = gene_name)) +
    geom_point()+
    #Creating gradient color representation
    scale_color_gradient(low = "blue", high = "red")+
    scale_x_continuous("Gene Frequency")+
    scale_y_continuous(paste0(cont_covariate))+
    labs(title = paste0('Gene Expression ', gene_name, ' vs. ', cont_covariate))+
    #Creating smooth trendline
    geom_smooth(aes(color=..y..), method = "loess", se = FALSE)+
    project_theme
  print(scatterplot)

  #Code to create boxplot
  boxplot <- ggplot(cleanedData,aes_string(x = cat_covariate1,y = gene_name,fill = cat_covariate2)) +
    # Add box plot
    geom_boxplot(color = "white") +
    scale_fill_manual(values = c("red", "purple"))+
    # Change labels
    labs(x = paste(cat_covariate1),y = paste0(gene_name, ' Gene Frequency'),fill = 
           paste(cat_covariate2), title = paste0(gene_name, ' Gene Frequency by ', 
                            cat_covariate1, ' and ', cat_covariate2))+
    project_theme
  print(boxplot)
}

#Calling the function with one gene example
# project_plots(df_name = combinedData, gene_name = 'AAAS', cont_covariate = 
#'hospital.free_days_post_45_day_followup', cat_covariate1 = 'sex', cat_covariate2 = 'icu_status')

#Creating loop to go though multiple genes
multiple_gene_selection <- c('AAAS', 'AAGAB', 'AAMDC')
for (gene in multiple_gene_selection){
  project_plots(df_name = combinedData, gene_name = gene, cont_covariate = 
    'hospital.free_days_post_45_day_followup', cat_covariate1 = 'sex', cat_covariate2 = 'icu_status')
}
```

